### ISSUE TITLE
DXE-2447 command >> update-local  |  incomplete , possible missing arguments

### ISSUE THREAD

**Issue by tpimenta88** [akamai/cli-promotional-deployment#83]
**akamai property-manager update-local -p qa.example.com**

i assume that **qa.example.com** is the property's name inside the Property Manager in the akamai portal.
when the command is run, how does it know the environment and pipeline to update locally?
keep getting the error : 
_PM CLI Error: 'property_folder_does_not_exist' occurred: 
 Error: Property folder 'qa.example.com' does not exist
    at DevopsPropertyManager.updateProperty (/Users/xx/.akamai-cli/src/cli-property-manager/src/pm/devops_property_manager.js:162:19)
    at update (/Users/xx/.akamai-cli/src/cli-property-manager/src/pm/property_manager_cli.js:698:44)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error details: 
        Argument #0:  qa.example.com

and the reality is the folder does not exist, what we have is env>qa
in a directory structure as follows:
>\example.com (pipeline name)
  >> \cache
   >>\dist
   >>\env
        >\\qa
        >\\prod

so should we not have to specify the property we want to fetch and the pipeline+environment to update???
Should the command look like:
akamai property-manager update-local -p <property_name in PM>  -p   pipelineName <environment_name>

**Comment by Slonimskaia** [comment]
Hi @tpimenta88,

Thank you for raising this issue. We will reproduce it from our side and come back to you soon.

Best regards,
Tatiana

**Comment by tpimenta88** [comment]
> **akamai property-manager update-local -p qa.example.com**
> 
> i assume that **qa.example.com** is the property's name inside the Property Manager in the akamai portal. when the command is run, how does it know the environment and pipeline to update locally? keep getting the error : _PM CLI Error: 'property_folder_does_not_exist' occurred: Error: Property folder 'qa.example.com' does not exist at DevopsPropertyManager.updateProperty (/Users/xx/.akamai-cli/src/cli-property-manager/src/pm/devops_property_manager.js:162:19) at update (/Users/xx/.akamai-cli/src/cli-property-manager/src/pm/property_manager_cli.js:698:44) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) Error details: Argument #0: qa.example.com
> 
> and the reality is the folder does not exist, what we have is env>qa in a directory structure as follows:
> 
> > \example.com (pipeline name)
> > > \cache
> > > \dist
> > > \env
> > > >\qa
> > > >\prod
> 
> so should we not have to specify the property we want to fetch and the pipeline+environment to update??? Should the command look like: akamai property-manager update-local -p <property_name in PM> -p pipelineName <environment_name>
So FROM: "-p <property_name in PM>" update-local pipeline & env, the TO :"-p pipelineName <environment_name>"
